CREATE database spring_demo DEFAULT CHARSET = UTF8;

USE spring_demo;

CREATE TABLE user(
  id INT AUTO_INCREMENT PRIMARY KEY  COMMENT "ID",
  username VARCHAR(30) NOT NULL COMMENT "用户名",
  password VARCHAR(32) NOT NULL COMMENT "密码",
  email VARCHAR(25) NOT NULL COMMENT "邮箱"
)ENGINE = InnoDB, DEFAULT CHARSET = UTF8;

CREATE TABLE seckill_good(
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT "Id",
  name VARCHAR(30) NOT NULL COMMENT "商品名称",
  store_count INT NOT NULL DEFAULT 0 COMMENT "商品剩余数量"
)ENGINE = InnoDB, DEFAULT CHARSET = UTF8;

CREATE TABLE seckill_order(
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT "Id",
  user_id INT NOT NULL COMMENT "用户Id",
  seckill_good_id INT NOT NULL COMMENT "秒杀商品Id",
  count INT NOT NULL DEFAULT 1 COMMENT "秒杀数量"
)ENGINE = InnoDB, DEFAULT CHARSET = UTF8;