CREATE database spring_demo DEFAULT CHARSET = UTF8;

USE spring_demo;

CREATE TABLE user(
  id INT AUTO_INCREMENT PRIMARY KEY  COMMENT "ID",
  username VARCHAR(30) NOT NULL COMMENT "用户名",
  password VARCHAR(32) NOT NULL COMMENT "密码",
  email VARCHAR(25) NOT NULL COMMENT "邮箱"
)ENGINE = InnoDB, DEFAULT CHARSET = UTF8;